{
    "openapi": "3.0.0",
    "info": {
        "title": "API Barber Web",
        "description": "Esta API tem como objetivo a manipulção de todo o sistema, persistir no banco de dados e fornecer informações importantes para o usuário final",
        "contact": {
            "email": "devmlima@gmail.com"
        },
    "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/",
            "description": "API de desenvolvimento"
        },
        {
            "url": "https://www.adefinir/",
            "description": "API de produção"
        }
    ],
    "paths": {
        "/users/find": {
            "get": {
                "description": "Busca todos os usuários cadastrados",
                "sumary": "Busca todos os usuários cadastrados",
                "tags": ["User"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "query",
                        "description": "Id do usuário para busca",
                        "required": false
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/findById/{id}": {
            "get": {
                "description": "Busca todos os usuários cadastrados por id",
                "sumary": "Busca todos os usuários cadastrados por id",
                "tags": ["User"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do usuário para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/update": {
            "put": {
                "description": "Atualiza os dados do usuário cadastrado",
                "sumary": "Atualiza os dados do usuário cadastrado",
                "tags": ["User"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"objeto",
                        "in": "path",
                        "description": "Objeto que contêm os conteúdos para atualização, é obrigatório enviar o id dentro do objeto.",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "company": {
                                    "value": {
                                        "id": 4,
                                        "nome": "Matheus Lima"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "Registro atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/delete/{id}": {
            "delete": {
                "description": "Apaga o usuário passado por id",
                "sumary": "Apaga o usuário passado por id",
                "tags": ["User"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do usuário para busca e deleção",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Usuário não encontrado"
                    },
                    "200": {
                        "description": "Registro excluído com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/signUp": {
            "post": {
                "sumary": "Cadastra um novo usuário",
                "description": "Essa rota será responsável por cadastrar um novo usuário no sistema",
                "tags": ["User"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "company": {
                                    "value": {
                                        "nome": "Matheus",
                                        "cpf": "78390646048",
                                        "email": "devmlima@gmail.com",
                                        "celular": "31973491438",
                                        "senha": "12345678",
                                        "dataNascimento": "27/09/1999",
                                        "empresa": {
                                            "cpfCnpj": "16680422000195",
                                            "razaoSocial": "Barbearia WEB",
                                            "nomeFantasia": "Barber",
                                            "telefone": "31973491438"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Usuário já cadastrado"
                    },
                    "200": {
                        "description": "Cadastro realizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "sumary": "Acessa o sistema",
                "description": "Essa rota será responsável por permitir o usuário acessar o sistema",
                "tags": ["User"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "company": {
                                    "value": {
                                        "nome": "Matheus",
                                        "cpf": "78390646048",
                                        "email": "devmlima@gmail.com",
                                        "celular": "31973491438",
                                        "senha": "12345678",
                                        "dataNascimento": "27/09/1999",
                                        "empresaId": 2
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Usuário já cadastrado"
                    },
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },

        "/company/create": {
            "post": {
                "sumary": "Cadastra uma nova empresa",
                "description": "Essa rota será responsável por cadastrar uma nova empresa no sistema",
                "tags": ["Company"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Company"
                            },
                            "examples": {
                                "company": {
                                    "value": {
                                        "cpfCnpj": "55006020000161",
                                        "enderecoId": 1,
                                        "razaoSocial": "Empresa Barbearia",
                                        "nomeFantasia": "Barbearia",
                                        "telefone": "31973491438"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Empresa já cadastrada"
                    },
                    "200": {
                        "description": "Cadastro realizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Company"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/company/find": {
            "get": {
                "description": "Busca todas as empresas cadastradas",
                "sumary": "Busca todas as empresas cadastradas",
                "tags": ["Company"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "query",
                        "description": "Id da empresa para busca",
                        "required": false
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/Company"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/company/findById/{id}": {
            "get": {
                "description": "Busca todas as empresas cadastradas por id",
                "sumary": "Busca todas as empresas cadastradas por id",
                "tags": ["Company"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id da empresa para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Company"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/company/update": {
            "put": {
                "description": "Atualiza os dados da empresa cadastrada",
                "sumary": "Atualiza os dados da empresa cadastrada",
                "tags": ["Company"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"objeto",
                        "in": "path",
                        "description": "Objeto que contêm os conteúdos para atualização, é obrigatório enviar o id dentro do objeto.",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "Registro atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Company"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/company/delete/{id}": {
            "delete": {
                "description": "Apaga a empresa passada por id",
                "sumary": "Apaga a empresa passada por id",
                "tags": ["Company"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id da empresa para busca e deleção",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Empresa não encontrada"
                    },
                    "200": {
                        "description": "Registro excluído com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Company"
                                }
                            }
                        }
                    }
                }
            }
        },
        
        "/client/create": {
            "post": {
                "sumary": "Cadastra um novo cliente",
                "description": "Essa rota será responsável por cadastrar um novo cliente no sistema",
                "tags": ["Client"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Client"
                            },
                            "examples": {
                                "client": {
                                    "value": {
                                        "cpfCnpj": "39931659009",
                                        "enderecoId": 2,
                                        "empresaId": 2,
                                        "nome": "Matheus",
                                        "celular": "31973491438"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Cliente já cadastrada"
                    },
                    "200": {
                        "description": "Cadastro realizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Client"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/find": {
            "get": {
                "description": "Busca todos os clientes cadastrados",
                "sumary": "Busca todos os clientes cadastrados",
                "tags": ["Client"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "query",
                        "description": "Id do cliente para busca",
                        "required": false
                    },
                    {
                        "name":"empresaId",
                        "in": "query",
                        "description": "Id da empresa em que o cliente pertence para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/Client"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/findById/{id}": {
            "get": {
                "description": "Busca todos os clientes por id",
                "sumary": "Busca todos os clientes por id",
                "tags": ["Client"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do cliente para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Client"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/update": {
            "put": {
                "description": "Atualiza os dados do cliente cadastrado",
                "sumary": "Atualiza os dados do cliente cadastrado",
                "tags": ["Client"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"objeto",
                        "in": "path",
                        "description": "Objeto que contêm os conteúdos para atualização, é obrigatório enviar o id dentro do objeto",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "Registro atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Client"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/delete/{id}": {
            "delete": {
                "description": "Apaga a empresa passada por id",
                "sumary": "Apaga a empresa passada por id",
                "tags": ["Client"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do cliente para busca e deleção",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Cliente não encontrado"
                    },
                    "200": {
                        "description": "Registro excluído com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Client"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/address/create": {
            "post": {
                "sumary": "Cadastra um novo endereço",
                "description": "Essa rota será responsável por cadastrar um novo endereço no sistema",
                "tags": ["Address"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Address"
                            },
                            "examples": {
                                "client": {
                                    "value": {
                                        "rua": "Av. Brasil",
                                        "numero": 95,
                                        "cep": 30140001,
                                        "estadoId": "2",
                                        "cidadeId": "2",
                                        "empresaId": "2"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Endereço já cadastrada"
                    },
                    "200": {
                        "description": "Cadastro realizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Address"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/address/find": {
            "get": {
                "description": "Busca todos os endereços cadastrados",
                "sumary": "Busca todos os endereços cadastrados",
                "tags": ["Address"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "query",
                        "description": "Id do endereço para busca",
                        "required": false
                    },
                    {
                        "name":"empresaId",
                        "in": "query",
                        "description": "Id da empresa em que o endereço pertence para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/Address"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/address/findById/{id}": {
            "get": {
                "description": "Busca todos os endereços por id",
                "sumary": "Busca todos os endereços por id",
                "tags": ["Address"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do endereço para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Address"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/address/update": {
            "put": {
                "description": "Atualiza os dados do endereço cadastrado",
                "sumary": "Atualiza os dados do endereço cadastrado",
                "tags": ["Address"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"objeto",
                        "in": "path",
                        "description": "Objeto que contêm os conteúdos para atualização, é obrigatório enviar o id dentro do objeto",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "Registro atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Address"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/address/delete/{id}": {
            "delete": {
                "description": "Apaga o endereço passado por id",
                "sumary": "Apaga o endereço passado por id",
                "tags": ["Address"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do endereço para busca e deleção",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Endereço não encontrado"
                    },
                    "200": {
                        "description": "Registro excluído com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Address"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/city/find": {
            "get": {
                "description": "Busca todas as cidades cadastradas",
                "sumary": "Busca todas as cidades cadastradas",
                "tags": ["City"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "query",
                        "description": "Id da cidade para busca",
                        "required": false
                    },
                    {
                        "name":"descricao",
                        "in": "query",
                        "description": "Descrição da cidade para busca",
                        "required": false
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/City"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/city/findById/{id}": {
            "get": {
                "description": "Busca todas as cidades por id",
                "sumary": "Busca todas as cidades por id",
                "tags": ["City"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id da cidade para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/City"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/state/find": {
            "get": {
                "description": "Busca todos os estados cadastrados",
                "sumary": "Busca todos os estados cadastrados",
                "tags": ["State"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "query",
                        "description": "Id do estado para busca",
                        "required": false
                    },
                    {
                        "name":"descricao",
                        "in": "query",
                        "description": "Descrição do estado para busca",
                        "required": false
                    },
                    {
                        "name":"sigla",
                        "in": "query",
                        "description": "Sigla do estado",
                        "required": false
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/State"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/state/findById/{id}": {
            "get": {
                "description": "Busca todos os estados por id",
                "sumary": "Busca todos os estados por id",
                "tags": ["State"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do estado para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/State"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/profile/create": {
            "post": {
                "sumary": "Cadastra um novo perfil",
                "description": "Essa rota será responsável por cadastrar um novo perfil no sistema",
                "tags": ["Profile"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Profile"
                            },
                            "examples": {
                                "company": {
                                    "value": {
                                        "permissoes": {"company": ["read", "upsert", "delete"], "client": ["read", "upsert", "delete"], "address": ["read", "upsert", "delete"], "city": ["read"], "state": ["read"], "profile": ["read", "upsert", "delete"], "user": ["read", "upsert", "delete"]},
                                        "empresaId": 2,
                                        "usuarioId": 2
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Empresa já cadastrada"
                    },
                    "200": {
                        "description": "Cadastro realizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Company"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/profile/find": {
            "get": {
                "description": "Busca todos os perfis cadastrados",
                "sumary": "Busca todos os perfis cadastrados",
                "tags": ["Profile"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"usuarioId",
                        "in": "query",
                        "description": "Id do usuário para busca do perfil",
                        "required": false
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref": "#/components/schemas/Profile"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/profile/findById/{usuarioId}": {
            "get": {
                "description": "Busca todos os perfis cadastrados por usuarioId",
                "sumary": "Busca todos os perfis cadastrados por usuarioId",
                "tags": ["Profile"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"usuarioId",
                        "in": "path",
                        "description": "Id do usuário para busca do perfil",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Profile"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/profile/update": {
            "put": {
                "description": "Atualiza os dados do perfil cadastrado",
                "sumary": "Atualiza os dados do perfil cadastrado",
                "tags": ["Profile"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"objeto",
                        "in": "path",
                        "description": "Objeto que contêm os conteúdos para atualização, é obrigatório enviar o id dentro do objeto.",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "200": {
                        "description": "Registro atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Profile"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/profile/delete/{usuarioId}": {
            "delete": {
                "description": "Apaga o perfil passado por usuarioId",
                "sumary": "Apaga o perfil passado por usuarioId",
                "tags": ["Profile"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id do usuário para busca e deleção do perfil",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Não autorizado"
                    },
                    "400": {
                        "description": "Perfil não encontrado"
                    },
                    "200": {
                        "description": "Registro excluído com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Profile"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Company": {
                "type": "object",
                "properties": {
                    "cpfCnpj": {
                        "type": "string"
                    },
                    "enderecoId": {
                        "type": "number"
                    },
                    "razaoSocial": {
                        "type": "string"
                    },
                    "nomeFantasia": {
                        "type": "string"
                    },
                    "telefone": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            },
            "Client": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "empresaId": {
                        "type": "number"
                    },
                    "enderecoId": {
                        "type": "number"
                    },
                    "cpfCnpj": {
                        "type": "string"
                    },
                    "celular": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            },
            "Address": {
                "type": "object",
                "properties": {
                    "rua": {
                        "type": "string"
                    },
                    "numero": {
                        "type": "number"
                    },
                    "cep": {
                        "type": "string"
                    },
                    "estadoId": {
                        "type": "number"
                    },
                    "cidadeId": {
                        "type": "number"
                    },
                    "empresaId": {
                        "type": "number"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            },
            "City": {
                "type": "object",
                "properties": {
                    "descricao": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            },
            "State": {
                "type": "object",
                "properties": {
                    "sigla": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            },
            "Profile": {
                "type": "object",
                "properties": {
                    "permissoes": {
                        "type": "string"
                    },
                    "usuarioId": {
                        "type": "number"
                    },
                    "empresaId": {
                        "type": "number"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            },
            "User": {
                "type": "object",
                "properties": {
                    "expiresIn": {
                        "type": "string"
                    },
                    "token": {
                        "type": "string"
                    },
                    "dataNascimento": {
                        "type": "string"
                    },
                    "celular": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "cpf": {
                        "type": "string"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "empresaId": {
                        "type": "number"
                    },
                    "id": {
                        "type": "number"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}